Updates from bedrock
mozilla-l10n/www-l10n pull request #123
Opened 2020-10-22 19:00 UTC by MozmarRobot

From file changes in https://github.com/mozilla/bedrock/commit/92186df9456736665bb2d95f1488cc9baa413032

2020-10-22 19:01 UTC, amychurchwell commented
@peiying2 this seems to have the correct updates. I am not sure why the other PR was generated... 🤔

2020-10-22 22:11 UTC, peiying2 requested changes
@amychurchwell 
- The Quantumn file looks good now, thanks for the fix.
- A few comments here and there in the FAQ
- General consistency issue with hyperlinked text in the FAQ page. Should the punctuation be outside the link? It's half and half throughout the page. I didn't call them out but please go through them and make changes.

2020-10-22 22:11 UTC, peiying2 commented on en/firefox/faq.ftl
> +firefox-does-not = { -brand-name-firefox } does not have a built-in VPN (virtual private network), but there are two products made by { -brand-name-mozilla }/{ -brand-name-firefox } that you can use
Should it be singular in `connection on WiFi` as in *either (singular) ABC or (singular) XYZ*?

2020-10-22 22:11 UTC, peiying2 commented on en/firefox/faq.ftl
> +firefox-is-made = { -brand-name-firefox } is made by { -brand-name-mozilla-corporation  }, a wholly owned subsidiary of the non-profit <a href="{ $url }">{ -brand-name-mozilla-foundation }</a>, and i
- Change from `non-profit` to `not-for-profit`
- { -brand-name-mozilla-corporation  } - extra space before closing bracket. Not sure if it matters.

2020-10-23 12:34 UTC, rraue commented on en/firefox/faq.ftl
> +firefoxs-default-search = { -brand-name-firefox }’s default search engine is { -brand-name-google }, which means you can search the web directly from the address bar. <a href="{ $url }">Learn more ab
@craigcook  had the idea to switch to "Google is the default search engine in Firefox" - lets go with this

2020-10-23 21:36 UTC, amychurchwell commented
pmac told me he is going to work on having the same PR update with changes instead of a new one being generated each time. 🎉

2020-10-23 22:22 UTC, peiying2 commented
The updates are reflected in #124.

2020-10-23 22:22 UTC, closed without merging