Updates from bedrock
mozilla-l10n/www-l10n pull request #127
Opened 2020-11-02 23:11 UTC by MozmarRobot

From file changes in https://github.com/mozilla/bedrock/commit/85770605eb3cc8a92a49785212b28b1bbd12dc6e

2020-11-03 00:24 UTC, peiying2 requested changes
@amychurchwell - new challenge, when a few of you are working on different PRs, the automated script includes all outstanding PRs, including ones that should not be part of the l10n PR. 

- Missed a few brands in the PR
- Quantum file keeps showing up in the PR. Let's remove it in the PR.
- WNP#83 is included, which is for German only. Let's move it in the PR.

2020-11-03 00:24 UTC, peiying2 commented on en/firefox/more.ftl
> +learn-more-about-firefox = Learn more about { -brand-name-firefox }, it’s history, features and mission
`it's` -> `its`

2020-11-03 00:24 UTC, peiying2 commented on en/firefox/more.ftl
> +firefox-more-firefox-chromebook = { -brand-name-firefox-browser } for Chromebook
`Chromebook` is a brand

2020-11-03 00:24 UTC, peiying2 commented on en/firefox/more.ftl
> +while-on-chromebook = While a Chromebook already has { -brand-name-chrome } installed, downloading and using Firefox as your go-to browser provides you with a few benefits
`Chromebook`, `Firefox` are brands

2020-11-03 00:24 UTC, peiying2 commented on en/firefox/more.ftl
> +firefox-quantum = Firefox Quantum
Both are brands

2020-11-03 00:24 UTC, peiying2 commented on en/firefox/more.ftl
> +quantum-was-revolution = Firefox Quantum was a revolution in Firefox development. In 2017, we created a new, lightning fast browser that constantly improves. Firefox Quantum is the { -brand-name-fire
`Firefox` and `Quantum` are both brands

2020-11-03 00:24 UTC, peiying2 commented on en/firefox/whatsnew/whatsnew-fx83.ftl
> +# This Source Code Form is subject to the terms of the Mozilla Public
Please remove this one from the PR. It is only for German.

2020-11-05 20:56 UTC, peiying2 commented
@amychurchwell before I proceed, I want to confirm that the string IDs are correct. I see a mixture of filename prefix and lack there of.

2020-11-09 17:09 UTC, amychurchwell commented
@peiying2 all new ID's should be prefixed correctly & I have removed the whatsnew page file.

2020-11-13 01:04 UTC, peiying2 reviewed
@amychurchwell I will go through the book.ftl file separately.

Given the length of this page, we are discussing with Justin on how to keep a content heavy page like this one to the target markets and offer an alternative, a shorter version to smaller communities. This page is best left for the l10n vendor to do. 

If you remove the book.ftl from this PR,  I will approve it.

2020-11-13 07:52 UTC, alexgibson commented
> If you remove the book.ftl from this PR, I will approve it.

@peiying2 I believe the EU team already have translations for DE and FR done and waiting just as soon as this is available in Pontoon. Couldn’t we configure the .ftl file to only be available in those locales? E.g. https://github.com/mozilla/bedrock/blob/master/l10n/configs/pontoon.toml#L136

2020-11-13 16:05 UTC, peiying2 commented
> > If you remove the book.ftl from this PR, I will approve it.
> 
> @peiying2 I believe the EU team already have translations for DE and FR done and waiting just as soon as this is available in Pontoon. Couldn’t we configure the .ftl file to only be available in those locales? E.g. https://github.com/mozilla/bedrock/blob/master/l10n/configs/pontoon.toml#L136

I am all for the temporary solution. Let's do that. This is just too much for any communities to go through.

2020-11-13 22:08 UTC, peiying2 requested changes
@amychurchwell if you are to push all the pages in one PR, make sure to configure the book.ftl to `de`, `fr` only for now. Once we transition to the Smartling platform, we can enable the other locales. This page needs to go to paid services to complete.

2020-11-13 22:08 UTC, peiying2 commented on en/firefox/privacy/book.ftl
> +privacy-book-for-each-of = <strong>Decide for each app:</strong> For each of the apps on your device that wants access to your location information, you can decide if you want to share it. All major
Remove `for` in `... operating systems allow for you to change...`

2020-11-13 22:08 UTC, peiying2 commented on en/firefox/privacy/book.ftl
> +privacy-book-another-reason-to = <strong>Avoid background localization:</strong> Another reason to do so is that some apps don’t only save your location when you use them – many of them also run the
`... some apps don’t only save your location ...` change `don't only save` to `not only save`.

2020-11-13 22:08 UTC, peiying2 commented on en/firefox/privacy/book.ftl
> +privacy-book-also-reconsider-the = <strong>Limit the access.</strong> Also, reconsider the permissions you once gave to the remaining apps, including social networks, and ask yourselves: Does this ap
Change `yourselves` to singular `yourself`.

2020-11-13 22:08 UTC, peiying2 commented on en/firefox/privacy/book.ftl
> +privacy-book-thirdparty-trackers-on = Third-party trackers, on the other hand, may log a visitor's entire website visit, for example for the purpose of displaying targeted ads to them. This even work
Insert a comma after example so it reads `... for example, for the purpose ...`

2020-11-19 00:48 UTC, peiying2 commented
Let me know if there are updates on this one. If the `book` can be separated from the PR, we can get the other files pushed through.

2020-11-20 00:04 UTC, amychurchwell commented on en/firefox/privacy/book.ftl
> +privacy-book-delete-your-browser = <strong>Delete your browser history.</strong> Whether you’re using { -brand-name-firefox }, { -brand-name-chrome }, { -brand-name-safari }, or a different product –
A list of recommendations follows this, so a link is not necessary. Will update the grammar though. 👍

2020-11-20 00:15 UTC, amychurchwell commented on en/firefox/privacy/book.ftl
> +privacy-book-bluetooth-is-a = Bluetooth is a great invention that can save us a lot of cable clutter. However, most people don’t use it permanently. If you don’t own a smartwatch or another device th
I think `removes a weak point that intruders might make use of` might work better

2020-11-20 00:24 UTC, amychurchwell commented
`book.ftl` is now in this PR: https://github.com/mozilla-l10n/www-l10n/pull/139
Recent changes from bedrock that were added to this PR are now here: https://github.com/mozilla-l10n/www-l10n/pull/140

2020-11-20 19:22 UTC, peiying2 commented
> `book.ftl` is now in this PR: #139
> Recent changes from bedrock that were added to this PR are now here: #140

Close the PR now.

2020-11-20 19:22 UTC, closed without merging