Add mozorg/about/governance/policies/participation.ftl
mozilla-l10n/www-l10n pull request #138
Opened 2020-11-19 19:17 UTC by amychurchwell

Ref: https://github.com/mozilla/bedrock/pull/9703

2020-11-19 19:18 UTC, amychurchwell commented
@peiying2 may I have your review for en before adding all the other locales?

2020-11-19 23:21 UTC, peiying2 requested changes
@amychurchwell Other than what's called out, the URLs are not called out separately in this file either, like the reporting PR.

2020-11-19 23:21 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-anyone-asked-to-stop = Anyone asked to stop unacceptable behavior is expected to comply immediately. Violation of these guidelines can result in you being ask to leave an event or onlin
- `... being ask ...` should be `... being asked ...`
- `... you being ask ...` - `you` here seems strange. It started as `Anyone asked to stop...`. Need to use a different pronoun.

2020-11-19 23:21 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-after-receiving-a = After receiving a concise description of your situation, they will review and determine next steps. In addition to conducting any investigation, they can provide a r
Add `the` so it reads `... determine the next steps.`

2020-11-19 23:21 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-ask-questions = Ask questions
Title case to stay consistent with other titles: `Ask Questions`

2020-11-19 23:21 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-license-and-attribution = License and attribution
Title case to stay consistent with other titles: `License and attribution`

2020-11-19 23:21 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-modifications-to-these = Modifications to these guidelines
Title case to stay consistent with other titles: `Modifications to these guidelines`

2020-11-19 23:21 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-everyone-is-encouraged = Everyone is encouraged to ask questions about these guidelines. If you are organizing an event or activity, reach out for tips building inclusion for your event
A word is missing after `tips`: `... reach out for tips building inclusion for your event ...`

2020-11-20 19:06 UTC, amychurchwell commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-otherwise-influencing = Otherwise influencing crowd actions that cause hostility in the session.
It reads to me like "any other kind of influencing crowd actions" I am not sure what the best grammar would be.

2020-12-01 23:21 UTC, amychurchwell commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-unwelcome-sexual-attention-or = Unwelcome sexual attention or unwelcome physical contact is not acceptable. This includes sexualized comments, jokes or imagery in interactions, communic
What about:

> Unwelcome sexual attention or unwelcome physical contact is not acceptable. This includes sexualized comments, jokes or imagery in interactions, communications or presentation materials, as well as inappropriate touching, groping, or sexual advances. Additionally, touching a person without permission, including sensitive areas such as their hair, pregnant stomach, mobility device (wheelchair, scooter, etc) or tattoos is unacceptable. This includes physically blocking or intimidating another person. Physical contact or simulated physical contact (such as emojis like “kiss”) without affirmative consent is not acceptable. The sharing or distribution of sexualized images or text is unacceptable.

2020-12-02 00:09 UTC, peiying2 commented on en/mozorg/about/governance/policies/participation.ftl
> +participation-otherwise-influencing = Otherwise influencing crowd actions that cause hostility in the session.
Let's use your suggested text instead.

2020-12-02 00:40 UTC, peiying2 approved these changes
Looks good. Thanks for reworking the long sentence. Please add the localized files.

2020-12-02 00:51 UTC, peiying2 approved these changes

2020-12-02 00:51 UTC, merged