Add firefox/browsers/best-browser.ftl
mozilla-l10n/www-l10n pull request #149
Opened 2020-12-03 13:45 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9746

2020-12-03 18:29 UTC, peiying2 requested changes

2020-12-03 18:29 UTC, peiying2 commented on en/firefox/browsers/best-browser.ftl
> +best-browser-firefox-is-offering = { -brand-name-firefox } is offering something new to keep you safe: <a href="{ $monitor }">{ -brand-name-firefox } Monitor</a>. It’s a free service that will alert
`Firefox Monitor` as a brand

2020-12-03 18:29 UTC, peiying2 commented on en-CA/firefox/browsers/best-browser.ftl
> +best-browser-today-is-a-different = Today is a different story. Ads, privacy hacks, security breaches, and fake news might have you looking at other qualities in a browser. How does the browser prote
Should be `Is it built` not `Does it built` in `Does it built to multitask...?`

2020-12-03 18:29 UTC, peiying2 commented on en-CA/firefox/browsers/best-browser.ftl
> +best-browser-in-the-mid-nineties = In the mid-nineties, Netscape, { -brand-name-ie } and AOL dominated the landscape. It was a simpler time when the sweet melody of dial-up internet rang across the l
`Netscape` shows up multiple times in the [browser history page](https://www-dev.allizom.org/en-US/firefox/browsers/browser-history/). Not sure if it is worth creating an entry. If not, I am fine with that. AOL doesn't appear to have any other mentions in the pages yet to be migrated.

2020-12-04 17:24 UTC, alexgibson commented
@peiying2 updated thanks

2020-12-04 17:32 UTC, peiying2 requested changes
Looks good, but we need to add an entry of Netscape to the brands.ftl file.

2020-12-04 17:38 UTC, alexgibson commented
Great catch! Added

2020-12-04 17:41 UTC, peiying2 approved these changes

2020-12-04 17:41 UTC, merged