Add mozorg/about.ftl
mozilla-l10n/www-l10n pull request #158
Opened 2021-01-04 14:56 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9827

2021-01-04 17:03 UTC, peiying2 requested changes
Overall looks good. A couple of things to call out:
- Removal of Taipei section, not sure how the layout will be affected.
- Need to have hoosteeno to get some clarity: not-for-profit or non-profit. We had issues with a few pages pushed out in the last days of the year because of conflicting info. We can keep them here as they are unless a decision was clearly written somewhere.

2021-01-04 17:15 UTC, alexgibson commented on en/mozorg/about.ftl
> +about-mozilla-puts-people-over-profit = { -brand-name-mozilla } puts people over profit in everything we say, build and do. In fact, there’s a non-profit Foundation at the heart of our enterprise.
This sentance relates specifically to the Foundation, so I think non-profit applies here?

2021-01-04 17:16 UTC, alexgibson commented on en/mozorg/about.ftl
> +about-corporation-foundation-not = Corporation. Foundation. Not-for-profit.
Not-for-profit probably applies here as it covers both Corporation and Foundation

2021-01-04 17:17 UTC, alexgibson commented on en/mozorg/about.ftl
> +about-taipei = Taipei
Good call, I'll work to remove this from the page.

2021-01-05 10:50 UTC, alexgibson commented
@peiying2 removed Taipei. Thank you for the review

2021-01-05 16:02 UTC, peiying2 approved these changes
Thank you for the fix. LGTM.

2021-01-05 16:02 UTC, merged