Add mozorg/about/manifesto.ftl
mozilla-l10n/www-l10n pull request #159
Opened 2021-01-07 09:25 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9829

2021-01-07 19:17 UTC, peiying2 requested changes
- A few related to brand name Mozilla Foundation
- Lightbeam and Maker Party are rarely used. Should we include them in brands.ftl? This is mostly to keep them in English, especially if we ask the vendor to translate some of the languages. It is an easier fix if there is a problem. But I am fine if we don't want to include the these two entries.

2021-01-07 19:17 UTC, peiying2 commented on en/mozorg/about/manifesto.ftl
> +manifesto-details-articulate-a-vision = articulate a vision for the internet that { -brand-name-mozilla } participants want the { -brand-name-mozilla } Foundation to pursue;
`the { -brand-name-mozilla } Foundation` -> `the { -brand-name-mozilla-foundation }`

2021-01-08 09:35 UTC, alexgibson commented
@peiying2 thanks for the review, updated.

2021-01-08 16:30 UTC, peiying2 approved these changes
Thanks for the fixes. LGTM!

2021-01-08 16:30 UTC, merged