Add mozorg/about/history.ftl
mozilla-l10n/www-l10n pull request #160
Opened 2021-01-14 10:38 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/issues/9805

2021-01-14 18:13 UTC, peiying2 commented on en/mozorg/about/history.ftl
> +history-in-2003-the-mozilla-project = In 2003, the { -brand-name-mozilla } project created the { -brand-name-mozilla } Foundation, an <a href="{ $foundation }">independent non-profit organization</a>
`the { -brand-name-mozilla } Foundation` -> `the { -brand-name-mozilla-foundation }`

2021-01-14 18:13 UTC, peiying2 requested changes
Overall looks good. Just one fix is needed.

2021-01-15 15:41 UTC, alexgibson commented
@peiying2 thank you, updated

2021-01-15 16:33 UTC, peiying2 approved these changes

2021-01-15 16:33 UTC, merged