Add 404.ftl and 500.ftl
mozilla-l10n/www-l10n pull request #161
Opened 2021-01-19 10:48 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9850

2021-01-19 18:14 UTC, peiying2 commented on en/404.ftl
> +not-found-page-learn-about-mozilla-the-non = <a href="{ $about }">Learn</a> about { -brand-name-mozilla }, the non-profit behind { -brand-name-firefox }.
Non-profit or not-for-profit?

2021-01-19 18:16 UTC, peiying2 requested changes
Looks good overall. Just one question on the use of `non-profit`. 
Another question is on the outdated strings. They were marked as obsolete strings 4 years ago. Should we consider removing them while we have a chance?

2021-01-20 09:56 UTC, alexgibson commented
@peiying2 thanks for the review. Fixed `not-for-profit` and removed the outdated strings.

2021-01-20 15:45 UTC, peiying2 approved these changes
Thank you for the updates. Looks good!

2021-01-20 15:46 UTC, merged