Add mozorg/about/legal.ftl
mozilla-l10n/www-l10n pull request #165
Opened 2021-02-03 10:54 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9891

2021-02-03 16:48 UTC, peiying2 requested changes
- One product name is missing
- Locale list for this file - should it be open to all?

2021-02-03 16:48 UTC, peiying2 commented on en/mozorg/about/legal.ftl
> +legal-firefox-services = { -brand-name-firefox } Services
Did we miss one entry `Firefox Better Web` which is a product name entry?

2021-02-03 16:48 UTC, peiying2 commented on configs/pontoon.toml
> +    locales = [
Should this be open to all locales rather than those with partial/full localization?

2021-02-04 15:02 UTC, alexgibson commented
Thanks @peiying2 - simplified the config, and also added the missing string (noticed a few more titles that have never been added too).

2021-02-04 17:17 UTC, peiying2 requested changes
@alexgibson The config file removes the entry Craig added for his PR yesterday. We need it for the set of privacy files. Other than that, it looks good.

2021-02-05 09:58 UTC, alexgibson commented
@peiying2 good catch, updated

2021-02-05 15:50 UTC, peiying2 approved these changes
Thanks for the fix. Looks good now.

2021-02-05 15:51 UTC, merged