Add mozorg/home.ftl
mozilla-l10n/www-l10n pull request #169
Opened 2021-02-09 09:55 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9919

2021-02-09 16:40 UTC, peiying2 requested changes
Looks good. Minor fix request.

2021-02-09 16:40 UTC, peiying2 commented on en/mozorg/home.ftl
> +home-did-you-know-mozilla-the-maker = Did you know? { -brand-name-mozilla } — the maker of { -brand-name-firefox } — fights to keep the Internet a global public resource, open and accessible to all.
`Internet` - lower case

2021-02-09 16:40 UTC, peiying2 commented on en-GB/mozorg/home.ftl
> +### URL: https://www-dev.allizom.org/ ('en-US', 'de' and 'fr' excluded)
seems like en-CA, en-GB are excluded too, by looking at the staging server.

2021-02-10 09:49 UTC, alexgibson commented
@peiying2 thanks updated

2021-02-10 16:04 UTC, peiying2 commented on en/mozorg/home.ftl
> +home-working-to-keep-the-internet = Working to keep the internet healthy, open and accessible to all, we teach web literacy, provide tools and advocate on behalf of every individual who values the In
Ooops, one more internet to fix at the end of this sentence: ...`who values the Internet as a global public resource.`

2021-02-10 16:05 UTC, peiying2 requested changes
Sorry, I missed one more capital initial for "internet'. This should be it, :).

2021-02-10 16:13 UTC, alexgibson commented
@peiying2 good catch updated

2021-02-10 16:15 UTC, peiying2 approved these changes
Thank you! Good to go!

2021-02-10 16:15 UTC, merged