Add firefox/retention/thank-you.ftl
mozilla-l10n/www-l10n pull request #170
Opened 2021-02-15 15:51 UTC by alexgibson

Ref: https://github.com/mozilla/bedrock/pull/9927

2021-02-15 15:52 UTC, alexgibson commented
@peiying2 I think this is the very last migration 🎉

2021-02-16 18:08 UTC, peiying2 requested changes
Other than removing "Send", a product no longer available,  it looks good. Also,  we need to remove the Send entries in the brands.ftl file.

2021-02-16 18:08 UTC, peiying2 commented on en/firefox/retention/thank-you.ftl
> +thank-you-send-a-tweet = { -brand-name-send } a tweet
Send is no longer available.  Let's remove it. And let's remove the entries in the  **brands.ftl** file as well

2021-02-17 14:31 UTC, alexgibson commented
@peiying2 updated thank you. Note we can't remove a brand name without also updating references to it in every .ftl file for the whole codebase. So rather than do that here I've added Firefox Send to the legacy products grouping.

2021-02-17 17:09 UTC, peiying2 reviewed
@alexgibson looks good. I will approve it. 

I do have a question. When strings with the same IDs are moved, would they appear as new strings in Pontoon, or they are magically rearranged in the localized file, thus the communities don't see the changes.

2021-02-17 17:12 UTC, alexgibson commented
> I do have a question. When strings with the same IDs are moved, would they appear as new strings in Pontoon, or they are magically rearranged in the localized file, thus the communities don't see the changes.

I'm not 100% sure, but it would appear as a change as far as Git is concerned. I'm not sure how Pontoon interprets that level of change though.

2021-02-17 17:44 UTC, peiying2 commented
> > I do have a question. When strings with the same IDs are moved, would they appear as new strings in Pontoon, or they are magically rearranged in the localized file, thus the communities don't see the changes.
> 
> I'm not 100% sure, but it would appear as a change as far as Git is concerned. I'm not sure how Pontoon interprets that level of change though.

Just checked with our tech expert, once the strings are translated, the string rearrangement won't trigger it to appear as a new string.

2021-02-17 17:45 UTC, peiying2 approved these changes

2021-02-17 17:45 UTC, merged