Updates from bedrock
mozilla-l10n/www-l10n pull request #277
Opened 2022-03-11 13:09 UTC by MozmarRobot

From file changes in https://github.com/mozilla/bedrock/commit/1ece0145ea3988340cbe453d48318126cae28b00

2022-03-15 19:04 UTC, peiying2 requested changes
brand name needs to be coded.

2022-03-15 19:04 UTC, peiying2 commented on en/banners/mozilla-connect.ftl
> +banner-mozilla-connect-content = Submit your ideas for Firefox and other Mozilla products and participate to conversations with Mozilla's product managers.
Brand names need to be coded.

2022-03-17 16:23 UTC, maureenlholland commented
@peiying2 we've updated to remove the unused banner file, let me know if there are any remaining issues

2022-03-17 17:40 UTC, peiying2 approved these changes

2022-03-17 17:41 UTC, merged