Updates from bedrock
mozilla-l10n/www-l10n pull request #281
Opened 2022-04-14 01:21 UTC by MozmarRobot

From file changes in https://github.com/mozilla/bedrock/commit/65ba9f405b0fa4715d48c612ba769458cee120e8

2022-04-14 04:25 UTC, peiying2 requested changes
- Use curly quote instead of straight.
- `Web` was replaced with lower case `web` at some point. There might be some inconsistency throughout the site, and even this page with. 
- Why we add the same strings in the `about.ftl` and the `about/shared.ftl`? Should we just add the new strings to `about/shared.ftl` only?

2022-04-14 04:25 UTC, peiying2 commented on en/mozorg/about.ftl
> +vision-for-the-web = { -brand-name-mozilla }'s vision for the Web
- Use Curly quote
- Web `Web` should be lower case

2022-04-14 04:25 UTC, peiying2 commented on en/mozorg/about.ftl
> +read-about-our-vision = Read about our vision for the Web and how we intend to pursue that vision.
`Web` should be lower case

2022-04-14 04:25 UTC, peiying2 commented on en/mozorg/about/shared.ftl
> +vision-for-the-web = { -brand-name-mozilla }'s vision for the Web
- Use Curly quote
- Web `Web` should be lower case

2022-04-14 04:25 UTC, peiying2 commented on en/mozorg/about/shared.ftl
> +read-about-our-vision = Read about our vision for the Web and how we intend to pursue that vision.
`Web` should be lower case

2022-04-14 04:26 UTC, peiying2 commented
@reemhamz

2022-04-18 20:50 UTC, reemhamz commented
Thanks for this Peiying! I'm just confirming a few things and will go forward from there.

2022-04-19 18:10 UTC, peiying2 commented
> Hi Peiying, So I [checked with the team](https://github.com/mozilla/bedrock/issues/11501#issuecomment-1101813945) and they'd like to keep the word `web` as capitalized (`Web`) wherever I placed the strings to translate, primarily because it's seen as a title. So we'll keep those as is. I'll also delete the strings from `about.ftl` since both pages will read `about/shared.ftl`. Thanks for catching that. I'll update the straight quotes to curly quotes also. A pull request will be merged soon for these changes

@reemhamz Thank you for the update. I understand the title case situation. What  about  the `Web` that is in a sentence?

2022-04-19 18:40 UTC, pmac commented
@peiying2 @k88hudson asked that we keep `Web` capitalized in https://github.com/mozilla/bedrock/issues/11501

2022-05-03 13:55 UTC, flodolo commented
I'm personally not a fan of having a [guideline](https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=FIREFOX&title=Word+List#WordList-web) and ignoring it, but given that's not a guideline explicitly set for mozilla.org, I think we should go ahead.

2022-05-03 13:56 UTC, merged