Updates from bedrock
mozilla-l10n/www-l10n pull request #426
Opened 2024-08-29 21:05 UTC by MozmarRobot

From file changes in https://github.com/mozilla/bedrock/commit/ba080c313c09c38e4fc26ba427fd13e9c66385d3

2024-08-29 21:34 UTC, peiying2 requested changes
Need to update string IDs for revised strings.

2024-08-29 21:34 UTC, peiying2 commented on en/firefox/all.ftl
> +firefox-all-browser = 1. Browser:
Make string ID `v2`

2024-08-29 21:34 UTC, peiying2 commented on en/firefox/all.ftl
> +firefox-all-platform = 2. Platform:
Make ID `v2`

2024-08-29 21:34 UTC, peiying2 commented on en/firefox/all.ftl
> +firefox-all-language = 3. Language:
Make string ID `v2`

2024-08-29 22:40 UTC, stephaniehobson commented
https://github.com/mozilla/bedrock/pull/15033

2024-08-29 22:44 UTC, peiying2 commented
> [mozilla/bedrock#15033](https://github.com/mozilla/bedrock/pull/15033)

@stephaniehobson Thank you for the fix. Do you want to label the `obsolete` strings and add a calendar date to them?

2024-08-30 00:00 UTC, peiying2 approved these changes
@stephaniehobson I approve the PR but please add the comments to the obsolete strings when you get a chance.

2024-08-30 00:00 UTC, merged

2024-08-30 18:30 UTC, stephaniehobson commented
Obsolete string dated: https://github.com/mozilla/bedrock/pull/15033