Updates from bedrock
mozilla-l10n/www-l10n pull request #454
Opened 2024-11-27 06:08 UTC by MozmarRobot

From file changes in https://github.com/mozilla/bedrock/commit/395be1b77e37804ac250e5852e8139328292f51d

2024-11-27 08:12 UTC, flodolo commented
@stephaniehobson @craigcook 
Is the goal to have this localized? Currently, it will only be localized by Smartling languages (paid agency, which covers French and German but not much more).

Otherwise, it needs to be added here https://github.com/mozilla/bedrock/blob/main/l10n/configs/pontoon.toml#L253-L301

2024-11-27 16:54 UTC, peiying2 commented on en/mozorg/about-m24.ftl
> +m24-about-at-our-rise25 = At our Rise25 Awards, the future of AI is trustworthy, inclusive and accountable
We need to add `Rise25` to the brands.ftl file per our discussion yesterday.

2024-11-27 16:58 UTC, peiying2 requested changes
Per our previous discussions, this page is open to the communities too, so let's add an entry in the pontoon.toml file, and add `Rise25` to the brands.ftl file.

2024-11-27 18:32 UTC, stephaniehobson commented
@peiying2 Ah sorry 🤦‍♀️ I did it for the homepage but not the about page.

2024-11-27 18:36 UTC, stephaniehobson commented
@flodolo yes, any community can translate it.

Is this the right thing to add?
```
[[paths]]
    reference = "en/mozorg/home-24.ftl"
    l10n = "{locale}/mozorg/home-24.ftl"
```

2024-11-27 18:39 UTC, peiying2 commented
> @flodolo yes, any community can translate it.
> 
> Is this the right thing to add?
> 
> ```
> [[paths]]
>     reference = "en/mozorg/home-24.ftl"
>     l10n = "{locale}/mozorg/home-24.ftl"
> ```

You can follow the format and add the new page in alphabetic order: https://github.com/mozilla-l10n/www-l10n/blob/f0072ba27f0c7f3cdd6231c3979a6fe7008a6157/configs/pontoon.toml#L253

2024-11-27 18:42 UTC, flodolo commented
> @flodolo yes, any community can translate it.
> 
> Is this the right thing to add?
> 
> ```
> [[paths]]
>     reference = "en/mozorg/home-24.ftl"
>     l10n = "{locale}/mozorg/home-24.ftl"
> ```

The file here is `en/mozorg/about-m24.ftl`, not `home-24.ftl`. Other than that, yes

2024-11-27 19:57 UTC, stephaniehobson commented
[PR with fixes](https://github.com/mozilla/bedrock/pull/15584).

2024-11-27 21:16 UTC, peiying2 commented on en/navigation_refresh.ftl
> +navigation-refresh-mozilla-ventures-v2 = { -brand-name-mozilla-venture }
Should be plural `{ -brand-name-mozilla-ventures }`

2024-11-27 21:20 UTC, peiying2 requested changes
Mozilla Ventures is plural. Also are you going to commit the other new file?

2024-12-02 17:47 UTC, peiying2 approved these changes

2024-12-02 17:49 UTC, merged